### ISSUE TITLE
Correction required: Creating a new release workflow

### ISSUE THREAD

**Issue by obervinov** [obervinov/_templates#10]
https://github.com/obervinov/_templates/blob/main/.github/workflows/create.release.yml#L15

**DESCRIPTION**:
Now the workflow for creating a new version of the module release on github provides for creation only for python-package, as it depends on the `pyproject.toml` file
```yaml
- name: Extract module version
   run: echo "version=v$(grep "version =" pyproject.toml | awk '{printf $3}' | sed 's/"//g')" >> $GITHUB_OUTPUT
   id: version
```
That's why creating releases for repositories other than python-package is now impossible

**Decision**:
To fix this situation, as well as to create a more universal workflow, it is necessary to fix the dependency with `pyproject.toml` on `CHANGELOG.md` (which should be in every repository)
