### ISSUE TITLE
Merge steps in wokrflow `pylint.yaml`

### ISSUE THREAD

**Issue by obervinov** [obervinov/_templates#54]
https://github.com/obervinov/_templates/blob/main/.github/workflows/pylint.yaml#L27-L31
```yaml
      - name: Install package dependencies and dependencies for testing  
        run: |
            poetry install
            poetry add --dev pylint flake8 pytest
```
