### ISSUE TITLE
Verify README.md template: not working with helm mono repository

### ISSUE THREAD

**Issue by obervinov** [obervinov/_templates#69]
**Describe the bug**
Verify README.md template:
 not working with helm mono repository

**To Reproduce**
https://github.com/obervinov/helm-charts/actions/runs/8694876452/job/23844704726

```yaml
---
name: Checks and Build Helm-Charts Bundle

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'

jobs:
  helm-repository-build:
    uses: obervinov/_templates/.github/workflows/helm.yaml@v1.0.12

  changelog:
    uses: obervinov/_templates/.github/workflows/changelog.yaml@v1.1.0
  
  readme:
    uses: obervinov/_templates/.github/workflows/readme.yaml@v1.1.0
```

```yaml
---
name: Create GitHub Release

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  helm-repository-build:
    uses: obervinov/_templates/.github/workflows/helm.yaml@v1.0.12

  changelog:
    uses: obervinov/_templates/.github/workflows/changelog.yaml@v1.1.0
  
  readme:
    uses: obervinov/_templates/.github/workflows/readme.yaml@v1.1.0

  create-release:
    uses: obervinov/_templates/.github/workflows/release.yaml@v1.1.0
    needs: [helm-repository-build, changelog, readme]

```
**Expected behavior**
workflow for testing https://github.com/obervinov/helm-charts/tree/main/.github/workflows
fix the line: https://github.com/obervinov/_templates/blob/main/.github/workflows/readme.yaml#L25
correct version:
```bash
% grep -oE '@(release/|fix/|hotfix/)?v[0-9]+\.[0-9]+\.[0-9]+' .github/workflows/release.yaml  
@v1.1.0
@v1.1.0
@v1.1.0
```

**Screenshots**
<img width="1761" alt="Снимок экрана 2024-04-15 в 23 28 32" src="https://github.com/obervinov/_templates/assets/49606362/2966971d-c8d1-49ff-b89f-eaca08985d2b">

**Additional context**
None

**Check list**
- [ ] Verify that the fix works
