### ISSUE TITLE
Feature request: automatic scheduled cleaning of untagged images in ghcr

### ISSUE THREAD

**Issue by obervinov** [obervinov/_templates#86]
**Is your feature request related to a problem? Please describe.**
Now images without tags created in PRs have to be cleaned manually, I would like to automate this process

**Describe the solution you'd like**
```yaml
  cleanup-untagged-images:
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged images from GitHub Container Registry
        continue-on-error: true
        uses: Chizkiyahu/delete-untagged-ghcr-action@v4
        with:
          token: ${{ secrets.PAT_GHCR_CLEANUP }}
          package_name: 'pyinstabot-downloader'
          untagged_only: true
          except_untagged_multiplatform: false
          owner_type: 'user'
```

**Describe alternatives you've considered**
An exploration of the possibilities is required.

**Additional context**
None
